### ISSUE TITLE
imagepath is broken

### ISSUE THREAD

**Issue by fooloomanzoo** [doclet/texdoclet#11]
The plugin is just generating **texdoclet_images**-folder but also does not find images located anywhere. It does not find it in the source folder, not relativly or absolutly or in the autogenerated folder.

**Comment by doclet** [comment]
Should be fixed now. Can you please check out the current version and make a maven build and test it ?
I guess you used -sourcepath with several paths separated by a colon ":" ? There was a bug in the code when finding the images by just considering the semicolon file separator ";".
