### ISSUE TITLE
A problem with square bracket

### ISSUE THREAD

**Issue by l-atome** [doclet/texdoclet#3]
I use your doclet since 1 week to provide manual to my student ...
I have a problem with array variable. For example a part of my code is : 
public Pion[] pions;

But after generate my javadoc, i have the followed code : 
\index{pions}
\label{ProjetCase.pions}public Pion {\bf  pions}\begin{itemize}

and the square bracket disappear ... Have I  forget some think ???

Very thanks for your apps ..
Thomas Castanet
Teacher of mathématics 
French lycée in Mali

**Comment by doclet** [comment]
Should be fixed now. 

For conformance reasons I also changed the font to true type for modifiers and types in section Fields  (methods and constructor sections using true type fonts too).
