### ISSUE TITLE
TexDoclet failes with string parsing error

### ISSUE THREAD

**Issue by jayjaybillings** [doclet/texdoclet#5]
I encountered the following error when I ran TexDoclet on my code. The code in question was about 91 packages from Eclipse ICE. I generated an Ant build file from the Eclipse Javadoc tool and then ran it from the command line. Here is the error:

  [javadoc] javadoc: error - In doclet class org.stfm.texdoclet.TeXDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
  [javadoc] java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  [javadoc]     at java.lang.String.substring(String.java:1931)
  [javadoc]     at org.stfm.texdoclet.TeXDoclet.classRelativeIdentifier(TeXDoclet.java:2134)
  [javadoc]     at org.stfm.texdoclet.TeXDoclet.printTags(TeXDoclet.java:2034)
  [javadoc]     at org.stfm.texdoclet.TeXDoclet.printMember(TeXDoclet.java:1750)
  [javadoc]     at org.stfm.texdoclet.TeXDoclet.printMember(TeXDoclet.java:1598)
  [javadoc]     at org.stfm.texdoclet.TeXDoclet.printMembers(TeXDoclet.java:1588)
  [javadoc]     at org.stfm.texdoclet.TeXDoclet.layoutClasses(TeXDoclet.java:1317)
  [javadoc]     at org.stfm.texdoclet.TeXDoclet.start(TeXDoclet.java:736)
  [javadoc]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  [javadoc]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  [javadoc]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  [javadoc]     at java.lang.reflect.Method.invoke(Method.java:497)
  [javadoc]     at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
  [javadoc]     at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
  [javadoc]     at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
  [javadoc]     at com.sun.tools.javadoc.Start.begin(Start.java:219)
  [javadoc]     at com.sun.tools.javadoc.Start.begin(Start.java:205)
  [javadoc]     at com.sun.tools.javadoc.Main.execute(Main.java:64)
  [javadoc]     at com.sun.tools.javadoc.Main.main(Main.java:54)

Any help would be much appreciated! Thanks for the great tool!

**Comment by doclet** [comment]
Fixed in commit 44253ec
